### ISSUE TITLE
Unable to enable csound-mode

### ISSUE THREAD

**Issue by jmalmari** [hlolli/csound-mode#1]
Hi. I installed csound-mode from melpa. Major mode failed with:

    Symbol’s function definition is void: reduce

For me, it started working when I replaced it with `cl-reduce`.

GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.19) of 2017-09-16

**Comment by hlolli** [comment]
Thanks for reporting on this, I see that reduce is an `defalias` of cl-reduce and I didn't require 'cl. Please post any issue if you encounter them or have a question.
