### ISSUE TITLE
Some requirements for Emacs26

### ISSUE THREAD

**Issue by sohet** [hlolli/csound-mode#10]
I need following init elisp before installing csound-mode (20191108.2359) from melpa to Emacs26 (GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars) of 2019-02-04, modified by Debian).
```
;; for lexical-let* in csound-score.el
(require 'cl)

;; for ->, ->> in csound-mode.el, csound-repl.el, csound-score.el, csound-util.el
(require 'subr-x)
(defalias '-> 'thread-first)
(defalias '->> 'thread-last)
```
Then repl and editing mode for orchestra and score work fine including eldoc, but font-lock does not seem to work there (no colored text). Enabled minor modes are,
```
Enabled minor modes: Auto-Composition Auto-Compression Auto-Encryption
Blink-Cursor Display-Time Eldoc Electric-Indent File-Name-Shadow
Font-Lock Global-Eldoc Global-Font-Lock Line-Number Mouse-Wheel
Shell-Dirtrack Tooltip Transient-Mark
```

**Comment by hlolli** [comment]
ah yeh. I'm getting these from dash.el. I'm going to add that. Since I'm a clojure developer, I find the thread first and thread second currently from dash. I'm also writing tests now, that should catch these regressions.

**Comment by sohet** [comment]
Thank you very much for the fix. The status on my Emacs26 is,

* need `(require 'subr-x)` for `string-join`
* need `(require 'cl)` for audio output in repl
* need something unknown for font-lock to work

**Comment by sohet** [comment]
After an awaiting fix, the status is,

- no need `(require 'subr-x)` on GNU Emacs 26.1 of 2019-09-23, modified by Debian (current Buster).
- no need `(require 'cl)` anymore.
- need `(with-eval-after-load 'csound-font-lock (setq csound-font-lock-list csound-font-lock-keywords))` in init.el for font-lock to work.
or replace each other `csound-font-lock-list` and `csound-font-lock-keywords` in csound-font-lock.el (and additional changes are required for emacs28 native compiler).

**Comment by sohet** [comment]
I find a rather straight solution for the last issue. Remove the first eval-when-compile from csound-font-lock.el and bite-compile it.
```
--- csound-font-lock.el.orig	2020-05-19 06:58:47.324292805 +0900
+++ csound-font-lock.el	2020-05-23 18:33:12.964624610 +0900
@@ -168,7 +168,6 @@
 
 (defconst csound-font-lock-keywords
   (ignore-errors
-    (eval-when-compile
       ;; Regex for i-rates
       (push '("\\<i+\\w*" . csound-font-lock-i-rate) csound-font-lock-list)
 
@@ -239,7 +238,7 @@
       (push '("\\<i\\'" . csound-font-lock-i) csound-font-lock-list)
       ;; Single line comments (use syntactic fontification?)
       (push '("//.*" . font-lock-comment-face)  csound-font-lock-list)
-      )))
+      ))
 
 
 ;; Borrowed from rainbow-delimiters.el
```

**Comment by sohet** [comment]
Now latest version (csound-mode-20230825.946 in melpa) resolves all the issues above.
