### ISSUE TITLE
problem on Catalina

### ISSUE THREAD

**Issue by Nanotk303** [hlolli/csound-mode#15]
Hi, 
i'm on Catalina and when i'm trying to C-c C-p for playing my csd, i get this message:
-*- mode: compilation; default-directory: "~/Csoundscores/" -*-
Compilation started at Thu Apr 23 12:41:06

csound -odac /Users/stephaneboussuge/Csoundscores/combostudy1.csd
zsh:1: command not found: csound

Compilation exited abnormally with code 127 at Thu Apr 23 12:41:06

Any help would be great !

thanks

Stéphane

**Comment by hlolli** [comment]
If you open the scratch buffer, and evaluate

```emacs
(getenv "PATH")
```

Does the path include the directory which the csound binary is in?

**Comment by Nanotk303** [comment]
No, indeed, Csound seem to be in /usr/local/bin but this is not listed by (getenv "PATH") .

How i can add /usr/local/bin to the path ?

Sorry for this question but i'm quit new to emacs...


SB.

**Comment by hlolli** [comment]
Best way to solve PATH issues from within emacs is to do it trough the shell, which emacs as process inherits. Looking at the error message, it seems that you started csound trough a zsh shell? In which case you'd want to add it to ~/.zshrc for bash shell it would be ~/.bashrc. Alternatively you can always set this in your ~/.emacs.d/init.el

```emacs
(setenv "PATH" (concat (getenv "PATH") ":/usr/local/bin"))
```

**Comment by Nanotk303** [comment]
I'm using zsh because when i start the shell, catalina ask to me to switch to zsh...
Anyway, you setenv trick did the job and now, csound mode works.

thank you for your help and for csound-mode , i'm waiting for it from long time, using csoundx in past...
I will test the repl who looks very interesting for me as a "traditionnal" csd composer....
Thanks again  !

SB.

**Comment by Nanotk303** [comment]
alast question, because i didn't saw in csound-mode doc:  How to stop csound after C-c C-p when compiling a csd ? i mean, how to interrupt it ?

SB.

**Comment by Nanotk303** [comment]
When doing C-c C-z to launch repl, i get a message:
csound is not installed on your computer....

but C-c C-p works fine and launch csound... strange..
