### ISSUE TITLE
[no match] for csound-mode on MELPA

### ISSUE THREAD

**Issue by michaelmariaott** [hlolli/csound-mode#22]
When trying to install the package from MELPA i get a [no match] error.

**Comment by hlolli** [comment]
which version are you currently getting from the melpa package list?

**Comment by michaelmariaott** [comment]
csound-mode is not listed on the package list at all. I am using the package list from "https://melpa.org/packages/". I can see the csound-mode package on the website, but when I fetch the list in emacs, csound-mode does not show up

Edit:
Never mind, mixed up init.el und .emacs. Works now. -.-'
