### ISSUE TITLE
Can not play sound by csound-play

### ISSUE THREAD

**Issue by sohet** [hlolli/csound-mode#25]
From the last update, I can not play sound out of box by csound-play (C-c C-p). If there is a need to remove "-odac" from the function, I think setting the default value of csound-play-flags to "-odac" in csound-mode.el is preferable. Without it csound-play only makes a test sound file for a starter.

**Comment by hlolli** [comment]
Yes, you are correct. I think this will prove to be problematic, rather I should make this configureable for those who want to customize their play script. I didn't pay much attention to that part of the PR, my apologies.

**Comment by hlolli** [comment]
I made what I feel is a proper solution, the default value of `csound-play-flags` is set to `-odac` so when a user changes it, they can make csound do whatever they want.

**Comment by rubenphilipp** [comment]
> Yes, you are correct. I think this will prove to be problematic, rather I should make this configureable for those who want to customize their play script. I didn't pay much attention to that part of the PR, my apologies.

Hey y'all,

I have to concede that this is apparently my, and not Hlöðver's, fault, as I -- in my pull request -- have changed the respective line (for obvious reasons, as pointed out in https://github.com/hlolli/csound-mode/issues/25#issuecomment-1567234711) without proper documentation. Anyway, I am glad we have got a proper solution now. 

Greetings
Ruben

**Comment by sohet** [comment]
Thank you Hlöðver for the quick fix, and thank you Ruben for the nice additions!
