### ISSUE TITLE
csound-skeleton does not update correctly

### ISSUE THREAD

**Issue by PvonN** [hlolli/csound-mode#35]
i changed the csound skeleton in the csound-sekeleton.el file my specific needs but it does not work correctly.
when i evaluate the new skeleton in csound-skeleton.el by hand and do the M-x csound-skeleton-new-csd it works like it should.
but when i start emacs new and do it again the skeleton is still the default one and i have to evaluate the new skeleton by hand for new.

can you give me a hint how to fix it? i also can do the fix and push it to the repo.

**Comment by hlolli** [comment]
However/wherever you are including and requiring csound-mode in your init.el. My guess is that your customization is loaded then csound-mode is imported/required and hance overrides your customization. You could use some of the init/post-init hooks to evaluate your customization at the right time.

**Comment by PvonN** [comment]
This is weird. 
I changed back and forth some stuff in my init.el but nothing changes:

(require 'csound-mode)
(use-package csound-mode
  :mode (("\\.csd\\'" . csound-mode)
         ("\\.orc\\'" . csound-mode)
         ("\\.sco\\'" . csound-mode)
         ("\\.udo\\'" . csound-mode))
  :load-path "/Users/philippneumann/.emacs.d/elpa/csound-mode/" )

And also:
when i actually change the csound-skeleton.el file - where does the csound mode find the default setting? This default template doesn't exist anymore, or am i wrong?

**Comment by PvonN** [comment]
Ok, i found now this error message:

Source file `....csound-skeleton.el' newer than byte-compiled file; using old file

My solution is to put this in my init.el:

(setq load-prefer-newer t)
